name: Build and Deploy

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install Dependencies
        working-directory: ./functions
        run: npm ci
        
      - name: Build
        working-directory: ./functions
        run: npm run build
        
      - name: Test
        working-directory: ./functions
        run: npm test
        if: false  # Отключено пока тесты не добавлены

  deploy:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Update extension.yaml version
        run: |
          sed -i "s/version: .*/version: ${VERSION#v}/" extension.yaml
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            extension.yaml
            functions/**/*
          body_path: CHANGELOG.md
          draft: false
          prerelease: false 